### ISSUE TITLE
Number of chains and cores

### ISSUE THREAD

**Issue by dsvanidze** [kaskr/tmbstan#18]
Dear @Cole-Monnahan-NOAA, @kaskr, 

In your examples you always use the same number of cores as the number of chains for parallelisation. For example:
```R
## Run in parallel with a init function
cores <- parallel::detectCores()-1
options(mc.cores = cores)
init.fn <- function()
  list(u=rnorm(114), beta=rnorm(2), logsdu=runif(1,0,10), logsd0=runif(1,0,1))
fit <- tmbstan(obj, chains=cores, open_progress=FALSE, init=init.fn)
```

Is it possible to run 4 chains on 32 or more cores? Or they should be always the same number? I would be grateful if you could help me to clarify this as soon as possible.

**Comment by Cole-Monnahan-NOAA** [comment]
Yes you can run any number of chains on any number of cores. For very slow analyses it is advisable to set chains <= cores just so that no core has to run more than one chain, essentially doubling the run time. From the `rstan::stan` documentation for argument `cores`:

````
The number of cores to use when executing the Markov chains in parallel. The default is to use the value of the "mc.cores" option if it has been set and otherwise to default to 1 core. However, we recommend setting it to be as many processors as the hardware and RAM allow (up to the number of chains). See detectCores if you don't know this number for your system.
````

**Comment by dsvanidze** [comment]
@Cole-Monnahan-NOAA thank you very much for your reply!

I see. As I mentioned, I have a server with 32 cpu cores. Because I run four Markov chains, `tmbstan` only uses four cpu cores. Is there a way to run `tmbstan` so that all 32 cores are used by four Markov chains? 

My model with a large data set in `tmbstan` takes 1-2 days to run 1,000 iterations and I need at least 10,000 iterations, which takes too much time (approximately two weeks). I think parallelisation of four Markov chains on all 32 cpu cores (if possible) can decrease run time significantly. Or are there other ways to decrease `tmbstan` run time ?

**Comment by Cole-Monnahan-NOAA** [comment]
No, using parallelization with cores for MCMC you cannot take advantage of the other 28 cores. You could try to rewrite your model to take advantage of parallel computations in the template. I'm not very familiar with that but there are examples and some built-in functionality, e.g., https://github.com/kaskr/adcomp/blob/master/TMB/inst/examples/linreg_parallel.R

That's the kind of route you want to go.  You might want to post to the TMB users group because I don't see a lot of guidance on TMB.

But to be clear, this is a TMB thing not a tmbstan thing. Once you get it working in TMB it'll work in tmbstan automatically.

**Comment by dsvanidze** [comment]
@Cole-Monnahan-NOAA I am very grateful for such a prompt reply. I will try as you recommended. Have a nice day!
